function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
    "Christmas would be incomplete without __________.",
    "King Tut brought __________ to the people of Arizona.",
    "Madonna is now embracing the curative powers of __________.",
    "Michael would've gotten away with it, if it hadn't been for __________.",
    "Gilligan discovered a primitive tribe that worships __________.",
    "Baseball fanatics came here to __________.",
    "I could tell you about _________, but then I'd have to kill you.",
    "You are invited to the theatre tonight to watch __________: The Musical.",
    "I'm having a problem with __________ and don't want your advice.",
    "Due to a bad mime joke, McDonalds no longer offers __________.",
    "During geometry class, I like to think about __________.",
    "She who controls __________ controls the world.",
    "I found out too late that you can't cheer up Godzilla with __________.",
    "Too bad I lost the instruction manual for __________.",
    "I'm sorry, Dr. Lisa, but I couldn't complete my homework because of __________.",
    "In Michael's final moments, __________ went through his mind.",
    "The Republicans started a rumor that the White House has a secret room devoted to __________.",
    "Sea World has opened an interactive exhibit on __________.",
    "In her new campaign song, Chelsea Clinton raps over the sounds of __________.",
    "In a new tourism campaign, Toronto announces that it has __________.",
    "Batman and Robin agree that __________ marked the beginning of Gotham's decline.",
    "In the new CrowdPublish.TV movie, Hannah struggles with __________ for the first time. ",
    "After George W. Bush became president, Santa started giving bad children __________ instead of coal.",
    "Sadly, kids these days are getting involved with __________.",
    "Life was difficult for cavemen before __________.",
    "I wrote a popular fan fiction book called Harry Potter and the Chamber of __________.",
    "Next on the Sports Channel: The World Cup of __________.",
    "Science will never explain the origin of __________.",
    "My PhD dissertation proves that 5th graders navigate mazes 65% slower after being exposed to __________.",
    "TSA regulations prohibit __________ on flights.",
    "The CIA interrogates US citizens by exposing them to __________.",
    "The Army has been airdropping __________ to the children of Iraq since 2005.",
    "Thanksgiving dinner was totally ruined by __________.",
    "England has declared that __________ is a basic human right.",
    "Life begins with a cry and ends with __________.",
    "Peace! What is it good for?",
    "Love is like ________. You get too much, you get too high.",
    "What is Santa Claus giving up for Lent?",
    "Who is buried in Grant's tomb?",
    "Let us always meet each other with smile, for the smile is the beginning of ________.",
    "We need to find God and He cannot be found in _________.",
    "The poverty of ________ is the greatest poverty",
    "I have found the paradox, that if you love until it hurts, there can be no more ________.",
    "Love begins at home, and it is not how much we do, but how much love we put in _________.",
    "We feel that what we are doing is just a drop in the ocean. But the ocean is _________ because it's missing that drop.",
    "If we have no peace, it's because we've forgotten _________.",
    "Let us not be satisfied with just giving money; they need your hearts. So spread ________ everywhere you go.",
    "If you can't feed a hundred people, then feed ________.",
    "________ is a fruit in season at all times, and within reach of every hand.",
    "The hunger for love is much more difficult to remove than the hunger for ________.",
    "If you want a message to be heard, it has to be sent out. To keep a lamp burning, we have to put ________ in it. -Mother Theresa",
    "_________?",
    "What the ________?",
    "Ride the reading __________.",
    "Hope, change, and _________.",
    "It is easier to find men who will volunteer to die, than to find those who are willing to _________.",
    "I came, I saw, I ________.",
    "Experience is the teacher of ________.",
    "It's better to create than to _________.",
    "If you must break the law, do it to seize ________.",
    "Cowards die many times before _________.",
    "I love the name of honor more than I fear _________.",
    "People are quick to believe that which they wish to be ________.",
    "Events of importance are the result of ________.",
    "No one is so brave that she is not disturbed by ________.",
    "I have lived long enough to satisfy ________.",
    "This is the dawning of the age of ________.",
    "I brought _________ back from Mars",
    "What did Michael eat for dessert?",
    "I broke up with my boyfriend because of __________.",
    "__________ only gets better after a few cheeseburgers.",
    "What helps Obama unwind?",
    "_______ is Kermit the Frog's guilty pleasure.",
    "_______ always livens up the funeral.",
    "_______: the car that keeps on driving.",
    "I'm on a fad diet that consists of green beans and ________.",
    "I found _________ in my soup.",
    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __________.",
    "When I go to prison, I'll have __________ smuggled in.",
    "When the Brady Bunch was cancelled, Moses called down a Plague of __________.",
    "When I die, I want my ashes scattered on ___________.",
    "After Dick Cheney shot his friend in the face, hunters started carrying _________.",
    "Maxwell House is good to the last _______.",
    "Kix: Kid-tested, mother-_______.",
    "Foot-in-________ disease",
    "__________: There's an app for that.",
    "Four score and seven years ago our mother ________",
    "One small step for women, one giant step for _______",
    "Do unto others as you'd have done to ___________.",
    "The Easter Bunny is such a ________.",
    "Don't even think about ________.",
    "I ordered a tuna sandwich, but got ________ instead.",
    "There's nothing to fear but __________.",
    "Do unto others as you'd have done to ___________.",
    "This is the dawning of the age of ________.",
    "I applied for a job as a ________.",
    "You can't always get what you want. But sometimes you might get ________.",
    "_______ explains why dinosaurs became extinct.",
    "Where did you discover the Black Plague?",
    "Why did the chicken cross the road?",
    "What caused the Big Bang?",
    "What ever happened to the Rubics Cube?",
    "Where is the Milky Way?",
    "When I grow up, I want to be _________.",
    "In October I will marry ________.",
    "I went to Neptune to see _________.",
    "You know you've arrived when the President names ________ in your honor.",
    "The fifth element on the periodic table is _________.",
    "Newton's second law states that Force equals _________ multiplied by acceleration.",
    "An eye for an eye, a tooth for _________.",
    "What did the priest just say?",
    "I met my husband at ________.",
    "Excuse me while I kiss ________.",
    "I joined a rock band called _________.",
    "The color of my new nail polish is _________.",
    "I made ________ for dinner.",
    "Money for nothing. And _________ for free.",
    "Might as well face it you're addicted to ________.",
    "Wrapped up like a ________ in the middle of the night.",
    "Jesus died for __________.",
    "Will Smith: the Fresh Prince of _________.",
    "The meaning of life is to justify _________.",
    "She blinded me with _________.",
    "A bird in the hand is worth __________."
  ];
}

function white() {
  return [
   "Phineas T. Barnum",
   "Little Jive Turkey",
   "Generic trees",
   "Hu Flung Pu",
   "Cactus clouds",
   "Washing the cat",
   "Reading a river",
   "Cantelope brains",
   "Emoticon conference",
   "Horse hell",
   "Zombie ducks",
   "Bacon cupcakes",
   "The place where the dryer hides your socks",
   "Monster ketchup",
   "Rainbow spout",
   "Horseshoe fly",
   "A messy flower",
   "Snoring aquariums",
   "Your little brother",
   "Mouthwash news",
   "A pinstriped hamster",
   "A waste of hair",
   "Peanut butter and sorrow sandwich",
   "Estate hood tax",
   "Popstar sicle",
   "Mustard gas greens",
   "Aerosmith space",
   "Gray poop on",
   "Foxhole trot",
   "Secret Asian man",
   "Lettuce spray",
   "Snow towels",
   "Gamesexchange",
   "Bikes in the fast lane",
   "Triangular coffee",
   "Pants on the Ground",
   "Time thief",
   "Super Nappingman",
   "Ten thousand fire tails",
   "Random word pants",
   "Worldwide Pants",
   "Singing eyeballs",
   "Fear beer",
   "Cod god",
   "Sage guage",
   "Batcat",
   "Fog dog",
   "Sitting on an x-ray",
   "Boring elbows",
   "Sore sidewalks",
   "Toothpaste ants",
   "The snore of a whale",
   "Fire chameleons",
   "Dancing t-shirts",
   "Purple people",
   "Pluto fly traps",
   "Texas toenails",
   "Sassy grass snakes",
   "Pickle popsicles",
   "The lack of a theme",
   "A purring dog",
   "A docile banshee",
   "A screaming mute",
   "Chartruse honeydew",
   "Smiling bulldogs",
   "Barking tigers",
   "Wormhole To Heaven",
   "A car driving in the ocean",
   "Formal tennis shoes",
   "Square tires",
   "Beef lollipops",
   "Disco waltzing",
   "Confederate communion",
   "Shy comedians",
   "Jumping snakes",
   "Flying trees",
   "Black headlights",
   "Clean bandit",
   "Star Peace",
   "Soul Mass Transit System",
   "Checkered Hair",
   "Strawberry feet",
   "Washington Native Americans",
   "Arizona Popes",
   "Snuggling roaches",
   "Church of the Buzzing Bees",
   "Stop sign scented candles",
   "Miss Take's English class",
   "The bus to Mars",
   "The river who says Ni",
   "Funky cold fire",
   "Burning down the swimming pool",
   "Perfect flaws",
   "Chemically enhanced shoelaces",
   "Staying awake for 5 years",
   "Melting flowers",
   "Bee side",
   "Neon lakes",
   "Red Hot Eggplants",
   "Spaceship from 1820",
   "A plane trip to Mesopotamia",
   "Sequinned songs",
   "Fish on a tricycle",
   "Driving a couch on a freeway",
   "Whirled cheese",
   "Sneaky corpses",
   "Solid oxygen",
   "Breathing carbon",
   "Blinking mouth",
   "Alice in Wonderbra",
   "The diary of a million year old rock",
   "Hungry like the proboscis",
   "Walk like a Hittite",
   "Theory of relatives",
   "Avocado's number",
   "The pyloric theorem",
   "Speed of fright",
   "State Pen University",
   "Hernia dog",
   "Super muffin",
   "Bronco Bama",
   "Leonardo DiCabriolet",
   "Matt Demon",
   "George Clowny",
   "Jake Gynocologichaal",
   "John Revolta",
   "Sean Penncil",
   "Humphrey Bogus",
   "Greta Garbled",
   "Sickgurney Weaver",
   "Susan Saranwrap",
   "George Snuffleupagus",
   "Brad Peach Pitt",
   "Normal Al Yankovic"


  ];
}

exports.getDeck = getDeck;
